/* Generated by AN DISI Unibo */ 
package it.unibo.firefly3

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly3 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var X = 7; var Y = 7; var RandomTime = 0L  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="randomFlashing", cond=doswitch() )
				}	 
				state("randomFlashing") { //this:State
					action { //it:State
						 RandomTime = kotlin.math.abs(java.util.Random().nextLong() % 1000) + 500  
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(RandomTime)
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						delay(RandomTime)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_randomFlashing", 
				 	 					  scope, context!!, "local_tout_"+name+"_randomFlashing", 50.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t010",targetState="randomFlashing",cond=whenTimeout("local_tout_"+name+"_randomFlashing"))   
					transition(edgeName="t011",targetState="wait_sync",cond=whenEvent("startSync"))
				}	 
				state("wait_sync") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Sincronizzata...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t112",targetState="flash",cond=whenEvent("sync"))
					transition(edgeName="t113",targetState="randomFlashing",cond=whenEvent("stopSync"))
				}	 
				state("flash") { //this:State
					action { //it:State
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(500) 
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_sync", cond=doswitch() )
				}	 
			}
		}
} 
