/* Generated by AN DISI Unibo */ 
package it.unibo.robotsmart

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Robotsmart ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 lateinit var planner : planning.AStarPathfinding   //Note lateinit		
				var Plan      = ""	
				var Caller    = ""
				var TargetX   = "" 
				var TargetY   = ""		 
				var X         = ""
				var Y         = "" 		
				var StepTime = "335"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 clearlog("./logs/robotsmart26.log") 			//vedi src/main/resources/logback.xml  
						CommUtils.outblue("$name | starts ")
						 logger.info(  "${currentState.stateName}: starts"  )  
						CommUtils.outyellow("$name | WAIT  before delegate ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="finishstart",cond=whenDispatch("partnerstarted"))
				}	 
				state("finishstart") { //this:State
					action { //it:State
						delegate("step", "robotmnemo") 
						delegate("move", "robotmnemo") 
						delegate("tuneAtHome", "robotmnemo") 
						delegate("getrobotstate", "robotmnemo") 
						delegate("getenvmap", "robotmnemo") 
						delegate("setrobotstate", "robotmnemo") 
						delegate("doplan", "planexec") 
						  planner = planning.AStarPathfinding(  )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("waitinputmsg") { //this:State
					action { //it:State
						CommUtils.outblue("$name | working ... ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="buildPlan",cond=whenRequest("buildPlan"))
					transition(edgeName="t02",targetState="domoverobot",cond=whenRequest("moverobot"))
					transition(edgeName="t03",targetState="dosetplanbuildelay",cond=whenDispatch("setplanbuildelay"))
				}	 
				state("dosetplanbuildelay") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("value(V)"), Term.createTerm("value(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("$name | dosetplanbuildelay done  ")
								 planner.setPlanBuildDelay( payloadArg(0).toInt() )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("domoverobot") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("moverobot(TARGETX,TARGETY,STEPTIME)"), Term.createTerm("moverobot(X,Y,STEPTIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 TargetX  = payloadArg(0)
												   TargetY  = payloadArg(1)
												   StepTime = payloadArg(2)
								request("setdirection", "dir(down)" ,"robotmnemo" )  
								CommUtils.outyellow("$name | setdirecton requested -----------------------------  ")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="planAndDomoves",cond=whenReply("setdirectiondone"))
				}	 
				state("planAndDomoves") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("pos(PX,PY)"), Term.createTerm("pos(PX,PY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  
										   val PX = payloadArg(0).toInt() 		//robotposutil.getPosX()
										   val PY = payloadArg(1).toInt() 		//robotposutil.getPosY()
										   Plan   = planner.planForGoal(PX,PY,TargetX.toInt(),TargetY.toInt()) 	   
								CommUtils.outgreen("$name | Plan-25 to reach ($TargetX,$TargetY) from ($PX,$PY) : $Plan")
								if(  Plan == "''"  
								 ){forward("noplan", "noplan(obstacle)" ,name ) 
								}
								else
								 {request("doplan", "doplan($Plan,$StepTime)" ,"planexec" )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="noplanfound",cond=whenDispatch("noplan"))
					transition(edgeName="t06",targetState="endMOveok",cond=whenReply("doplandone"))
					transition(edgeName="t07",targetState="endko",cond=whenReply("doplanfailed"))
				}	 
				state("noplanfound") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("endMOveok") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						answer("moverobot", "moverobotdone", "moverobotdone(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("endko") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("doplanfailed(PLANTODO)"), Term.createTerm("doplanfailed(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val PathTodo = payloadArg(0)  
								CommUtils.outred("$name | pos NOT reached - PathTodo = ${PathTodo} vs. $Plan")
								   var PathDone = Plan.substring(0, Plan.lastIndexOf(PathTodo))
												 if( PathDone == "" ) PathDone ="n"				 
								 				 //else planner.doPathOnMap(PathDone)
								CommUtils.outred("$name |  PathDone = ${PathDone} ")
								answer("moverobot", "moverobotfailed", "moverobotfailed($PathDone,$PathTodo)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("buildPlan") { //this:State
					action { //it:State
						 var Plan = "''"  
						if( checkMsgContent( Term.createTerm("buildPlan(PX,PY,TX,TY)"), Term.createTerm("buildPlan(PX,PY,TX,TY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  
											   val PX =  payloadArg(0).toInt() 
											   val PY = payloadArg(1).toInt()
											   val TX = payloadArg(2).toInt()
											   val TY = payloadArg(3).toInt()
											   Plan   = planner.planForGoal(PX,PY,TX,TY) 	    
											   if( Plan.isEmpty()) Plan="''"
											   //CommUtils.outcyan("$name | Plan-25 to reach ($TX,$TY) from ($PX,$PY) = $Plan")
								CommUtils.outblack("$name | Plan to reach ($TX,$TY) from ($PX,$PY) = $Plan")
								answer("buildPlan", "buildPlanDone", "buildPlanDone($Plan)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("fatalerror") { //this:State
					action { //it:State
						CommUtils.outred("fatalerror: attempt to reach a cell occupied ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
			}
		}
} 
