## ----------------------------------------------------------
## Dockerfile for  griddisplay
## ----------------------------------------------------------

FROM eclipse-temurin:17.0.5_8-jre-focal as builder
## EXPOSE 8085
## ADD extracts the tar
ADD ../build/distributions/griddisplay-1.0.tar /
WORKDIR /griddisplay-1.0/bin
COPY ./*.pl ./
COPY ./*.json ./
COPY ./*.bin ./
COPY ./*.txt ./

## RUN apt-get update -y
## RUN sudo apt-get install -y python

CMD ["bash", "griddisplay"]

## 0) docker rmi griddisplay-1.0-1.0
## 1) gradlew distTar
## 2) docker build -t griddisplay-1.0 .
 
## docker run -it --rm --name griddisplay -p8080:8080/tcp   griddisplay-1.0  /bin/bash
## docker run -it --rm --name griddisplay -p8080:8080/tcp   --privileged --env "HOST_IP=192.168.1.132" griddisplay-1.0  /bin/bash

# docker tag griddisplay-1.0 natbodocker/griddisplay-1.0

#type docker_password.txt | docker login --username natbodocker --password-stdin
#docker login --username natbodocker --password xyz
# docker push natbodocker/griddisplay-1.0

# docker-compose -f griddisplay.yaml  up