/* Generated by AN DISI Unibo */ 
package it.unibo.planexec

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Planexec ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		  var Plan          = ""
				var PlanOrig      = ""
				var Plantodo      = ""
				var CurMoveTodo   = ""		
				var StepTime      = "335"
				var ExecDelay     = 70L   //(B)
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="execAPlan",cond=whenRequest("doplan"))
				}	 
				state("execAPlan") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("doplan(PLAN,STEPTIME)"), Term.createTerm("doplan(PLAN,STEPTIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Plan       = payloadArg(0)  //.replace("[","").replace("]","").replace(",","").replace(" ","")
											   PlanOrig   = Plan
											   StepTime   = payloadArg(1)          //if int ...
								    		   val Caller = currentMsg.msgSender() //payloadArg(1) 
								updateResourceRep( "doing($name,plan=$Plan)"  
								)
								CommUtils.outyellow("$name | execAPlan nnnnnnnnnnnnnnn $StepTime Plan=$Plan")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="nextMove", cond=doswitch() )
				}	 
				state("nextMove") { //this:State
					action { //it:State
						 
								   if( Plan.length > 0  ){
								   	CurMoveTodo =  Plan.elementAt(0).toString() 
								   	Plan        =  Plan.removePrefix(CurMoveTodo)
								   }else{
								   	CurMoveTodo = ""
								   	Plan        = "empty"
								   } 		   
						if(  CurMoveTodo == ""  
						 ){forward("nomoremove", "nomoremove(end)" ,"planexec" ) 
						}
						else
						 {if(  CurMoveTodo == "w"  
						  ){delay(ExecDelay)
						 request("step", "step($StepTime)" ,"robotmnemo" )  
						 }
						 else
						  {CommUtils.outyellow("$name | doMoveTurn $CurMoveTodo")
						  forward("move", "move($CurMoveTodo)" ,"robotmnemo" ) 
						  delay(500) 
						  forward("nextmove", "nextmove(goon)" ,"planexec" ) 
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="planinterruptedobstacle",cond=whenReply("stepfailed"))
					transition(edgeName="t021",targetState="planinterrupted",cond=whenEvent("alarm"))
					transition(edgeName="t022",targetState="planend",cond=whenDispatch("nomoremove"))
					transition(edgeName="t023",targetState="nextMove",cond=whenDispatch("nextmove"))
					transition(edgeName="t024",targetState="nextMove",cond=whenReply("stepdone"))
				}	 
				state("planend") { //this:State
					action { //it:State
						CommUtils.outblue("$name | planend ok plan=$PlanOrig ")
						answer("doplan", "doplandone", "doplandone($PlanOrig)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("planinterruptedobstacle") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name |  planinterruptedobstacle CurMoveTodo=$CurMoveTodo Plan=$Plan StepTime=$StepTime")
						  Plantodo =  CurMoveTodo + Plan
						updateResourceRep( "planinterruptedobstacle($PlanOrig,$Plantodo )"  
						)
						answer("doplan", "doplanfailed", "doplanfailed($Plantodo)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("planinterrupted") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						updateResourceRep( "planinterrupted($PlanOrig,$Plantodo )"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t025",targetState="nonextmovesincealarm",cond=whenDispatch("nextmove"))
					transition(edgeName="t026",targetState="nonextmovesincealarm",cond=whenReply("stepdone"))
					transition(edgeName="t027",targetState="planinterruptedobstacle",cond=whenReply("stepfailed"))
				}	 
				state("nonextmovesincealarm") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name |  nonextmovesincealarm $CurMoveTodo plantodo=$Plan")
						updateResourceRep( "planfailed($PlanOrig,$Plan )"  
						)
						if(  Plan.length == 0  
						 ){answer("doplan", "doplandone", "doplandone($PlanOrig)"   )  
						}
						else
						 {answer("doplan", "doplanfailed", "doplanfailed($Plan)"   )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("planrefused") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | planrefused ")
						answer("doplan", "doplanfailed", "doplanfailed(youarenotowner)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
