/* Generated by AN DISI Unibo */ 
package it.unibo.robotsmart26planexec

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Robotsmart26planexec ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var PianoRimanente = ""
		        var MossaCorrente   = ""
		        var StepTime        = 330L
		        var PianoFallito    = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outblack("Pronto ad eseguire richieste di piano (doplan).")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="piano",cond=whenRequest("doplan"))
				}	 
				state("piano") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("doplan(PLAN,STEPTIME)"), Term.createTerm("doplan(PLAN,TIMESTEP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                // Puliamo la stringa rimuovendo spazi intermedi per isolare i singoli caratteri
								                PianoRimanente = payloadArg(0).replace(" ", "")
								                StepTime = payloadArg(1).toLong()
								CommUtils.outblack("Inizio esecuzione stringa piano: $PianoRimanente con StepTime: $StepTime")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="controllaPiano", cond=doswitch() )
				}	 
				state("controllaPiano") { //this:State
					action { //it:State
						
						            if (PianoRimanente.length == 0) {
						                forward("nomoremove", "nomoremove(done)", "robotsmart26planexec")
						            } else {
						                forward("nextmove", "nextmove(work)", "robotsmart26planexec")
						            }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="pianoFinito",cond=whenDispatch("nomoremove"))
					transition(edgeName="t02",targetState="estraiMossa",cond=whenDispatch("nextmove"))
				}	 
				state("estraiMossa") { //this:State
					action { //it:State
						
						            MossaCorrente = PianoRimanente.first().toString()
						            PianoRimanente = PianoRimanente.drop(1)
						CommUtils.outblack("Mossa estratta: $MossaCorrente | Rimanenti: $PianoRimanente")
						
						            if (MossaCorrente == "w") {
						                forward("nextmove", "nextmove(w)", "robotsmart26planexec")
						            } else {
						                forward("nextmove", "nextmove(skip)", "robotsmart26planexec")
						            }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="controllaTipoMossa",cond=whenDispatch("nextmove"))
				}	 
				state("controllaTipoMossa") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="esegui", cond=doswitchGuarded({ MossaCorrente == "w"  
					}) )
					transition( edgeName="goto",targetState="controllaPiano", cond=doswitchGuarded({! ( MossaCorrente == "w"  
					) }) )
				}	 
				state("esegui") { //this:State
					action { //it:State
						CommUtils.outblack("Esecuzione passo singolo 'w'. Rimanenti: $PianoRimanente")
						request("step", "step($StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="passoOk",cond=whenReply("stepdone"))
					transition(edgeName="t05",targetState="passoFallito",cond=whenReply("stepfailed"))
				}	 
				state("passoOk") { //this:State
					action { //it:State
						CommUtils.outblack("Singolo passo completato con successo.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="controllaPiano", cond=doswitch() )
				}	 
				state("passoFallito") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("stepfailed(DURATION,CAUSE)"), Term.createTerm("stepfailed(DURATION,CAUSE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblack("Errore o ostacolo incontrato, Causa: ${payloadArg(1)}")
								 
								                PianoFallito = MossaCorrente + PianoRimanente 
						}
						answer("doplan", "doplanfailed", "doplanfailed($PianoFallito)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="piano",cond=whenRequest("doplan"))
				}	 
				state("pianoFinito") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outblack("Intera sequenza di passi eseguita con successo.")
						answer("doplan", "doplandone", "doplandone(success)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="piano",cond=whenRequest("doplan"))
				}	 
			}
		}
} 
