/* Generated by AN DISI Unibo */ 
package it.unibo.firefly2

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly2 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
			   var  X          = 5
			   var  Y          = 5
			   var Timer       = 500L 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 Timer = java.util.Random().nextLong(1000L,2000L )   
						CommUtils.outblue("$name | X=$X Y=$Y  Timer=$Timer")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flash", cond=doswitch() )
				}	 
				state("flash") { //this:State
					action { //it:State
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(500) 
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flash", 
				 	 					  scope, context!!, "local_tout_"+name+"_flash", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t02",targetState="flash",cond=whenTimeout("local_tout_"+name+"_flash"))   
					transition(edgeName="t03",targetState="handle_sync",cond=whenEvent("sync"))
				}	 
				state("handle_sync") { //this:State
					action { //it:State
						 Timer = 1500L  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flash", cond=doswitch() )
				}	 
			}
		}
} 
