plugins {
    id 'java'
    id 'eclipse'
    id 'application'
}

repositories {
    mavenCentral()
    /* Cerca i file .jar personalizzati sia nella cartella superiore (standard Unibo)
       sia in una cartella 'libs' interna al progetto per sicurezza.
    */
    flatDir { 
        dirs '../unibolibs', './libs' 
    }
}

version '1.0'

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

dependencies {
    // TEST
    testImplementation group: 'junit', name: 'junit', version: '4.12'

    // WEBSOCKETS (OkHttp & Java-WebSocket)
    implementation group: 'com.squareup.okhttp3', name: 'okhttp', version: '4.9.3' 
    testImplementation group: 'com.squareup.okhttp3', name: 'mockwebserver', version: '4.9.3'
    implementation group: 'javax.websocket', name: 'javax.websocket-api', version: '1.1'
    implementation group: 'org.glassfish.tyrus.bundles', name: 'tyrus-standalone-client', version: '1.9'
    implementation group: 'org.java-websocket', name: 'Java-WebSocket', version: '1.6.0'

    // HTTP (Apache Components - Risolve gli errori org.apache.http)
    implementation 'org.apache.httpcomponents:httpclient:4.5.14'
    implementation 'org.apache.httpcomponents:httpcore:4.4.16'
    implementation 'commons-logging:commons-logging:1.2'

    // LOGGING
    implementation 'ch.qos.logback:logback-classic:1.4.12'
    implementation 'org.slf4j:slf4j-api:2.0.9'

    // JSON (Risolve gli errori org.json.simple)
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'

    // CUSTOM UNIBO (Assicurati che i .jar siano in ../unibolibs o ./libs)
    implementation name: '2p301'
    implementation name: 'uniboInterfaces'
    implementation name: 'unibo.basicomm23-1.0'
}

/* Configurazione dei sorgenti: 
   Gradle deve sapere che il codice si trova sia in 'src' che in 'utils'
*/
sourceSets {
    main {
        java {
            srcDirs = ['src', 'utils']
            exclude 'main/**'
        }
    }
}  

application {
    // Classe principale da eseguire
    mainClass = 'appls.BoundaryWithBasicMoves'
}

// Configurazione specifica per Eclipse per evitare conflitti di classpath
eclipse {
    classpath {
        downloadJavadoc = true
        downloadSources = true
    }
}