/* Generated by AN DISI Unibo */ 
package it.unibo.sistemas

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sistemas ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("Hello world")
						CommUtils.outblue("result=$V")
						CommUtils.outblack("now I'm waiting for a dispatch")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleEval",cond=whenDispatch("eval"))
					transition(edgeName="t01",targetState="handleRequest",cond=whenRequest("evalr"))
				}	 
				state("handleEval") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outmagenta("$name | msg=$currentMsg")
						if( checkMsgContent( Term.createTerm("arg(V)"), Term.createTerm("arg(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val VasString = payloadArg(0)
									  	   val V = VasString.toDouble()
								CommUtils.outgreen("$name | evaluate $V")
								 val R = eval(V)  
								CommUtils.outgreen("$name | result=$R")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("arg(V)"), Term.createTerm("arg(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val VasString = payloadArg(0)
								    		   val V = VasString.toDouble()
								CommUtils.outgreen("$name | evaluate $V")
								 val R = eval(V)  
								CommUtils.outblue("$name | result=$R")
						}
						answer("evalr", "evalreply", "value($V)"   )  
						CommUtils.outblue("$name | handleRequest ends")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleReply") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("value(V)"), Term.createTerm("value(x)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val VasString = payloadArg(0)  
								CommUtils.outmagenta("$name | result received=$VasString")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
