/* Generated by AN DISI Unibo */ 
package it.unibo.coordinator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Coordinator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
				var DMIN = 30 
				var IsSyncActive = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("Coordinator | In attesa del Sonar...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_work", 
				 	 					  scope, context!!, "local_tout_"+name+"_work", 1500.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="emitSyncSignal",cond=whenTimeout("local_tout_"+name+"_work"))   
					transition(edgeName="t01",targetState="handleSonar",cond=whenEvent("sonar_data"))
				}	 
				state("handleSonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Distance = payloadArg(0).toInt()  
								if(  Distance < DMIN  
								 ){if(  !IsSyncActive  
								 ){emit("startSync", "startSync(1)" ) 
								 IsSyncActive = true  
								CommUtils.outgreen("Coordinator | SYNC ATTIVATO")
								}
								}
								else
								 {if(  IsSyncActive  
								  ){emit("stopSync", "stopSync(1)" ) 
								  IsSyncActive = false  
								 CommUtils.outgreen("Coordinator | SYNC DISATTIVATO")
								 }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("emitSyncSignal") { //this:State
					action { //it:State
						if(  IsSyncActive  
						 ){emit("sync", "sync(1)" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
