services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi26:1.0
    #image: virtualrobotdisi26:1.0
    ports:
     - 8090:8090
     - 8091:8091
    networks:
     - iss-network
  
 
networks:
    iss-network:
     external: true

## docker-compose -f vr26Alone.yaml up
## docker-compose down
## docker-compose run --service-ports wenv    starts wenv

## docker network ls
## docker network create iss-network
## docker network rm x
