/* Generated by AN DISI Unibo */ 
package it.unibo.robotmnemo

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Robotmnemo ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val rpos = smart.RobotPosUtils.getInstance("localhost")
		val robot = robots.VRObjForQak(myself,"logs/robotsmart26.log")
		 var doingAsynchStep = false   
		  	   var CurTime         = 0L	   
		 	   var StepTime        = 335
		 	   var Plan            = "" 
		 	   var MoveForDir      = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						forward("partnerstarted", "partnerstarted($MyName)" ,"robotsmart" ) 
						CommUtils.outblue("$name STARTS ${rpos.getGuiIp() }")
						 clearlog("./logs/robotmnemo.log") 	//vedi src/main/resources/logbdomoveack.xml  
						subscribeToLocalActor("robotmnemo") 
						subscribeToLocalActor("robotmnemo") 
						CommUtils.outblue("$name subscribe to myself done")
						 robot.connect( rpos.getGuiIp() )  
						CommUtils.outblue("$name | at home. GUI on ...")
						  rpos.robotAtHome(   )  
						delay(500) 
						delegate("doplan", "planexec") 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("waitinputmsg") { //this:State
					action { //it:State
						  rpos.showTheRobotState(   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="domove",cond=whenDispatch("move"))
					transition(edgeName="t09",targetState="dosetrobotstate",cond=whenDispatch("setrobotstate"))
					transition(edgeName="t010",targetState="dosetrobotdirection",cond=whenRequest("setdirection"))
					transition(edgeName="t011",targetState="dogetrobotstate",cond=whenRequest("getrobotstate"))
					transition(edgeName="t012",targetState="doAsynchStep",cond=whenRequest("step"))
					transition(edgeName="t013",targetState="doGetEnvMap",cond=whenRequest("getenvmap"))
					transition(edgeName="t014",targetState="tuneAtHome",cond=whenRequest("tuneAtHome"))
				}	 
				state("dogetrobotstate") { //this:State
					action { //it:State
						  val PX  = rpos.getPosX() 
						    		val PY  = rpos.getPosY() 
						    		val DIR = rpos.getCurDir() 
						answer("getrobotstate", "robotstate", "robotstate(pos($PX,$PY),$DIR)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("dosetrobotstate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("setpos(X,Y,D)"), Term.createTerm("setpos(X,Y,D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								 				val X = payloadArg(0).toInt()
								 				val Y = payloadArg(1).toInt()
								 				val D = payloadArg(2)
								 rpos.setRobotState(X,Y,D)  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("doAsynchStep") { //this:State
					action { //it:State
						CurTime = getCurrentTime()
						updateResourceRep( "doing($name,doAsynchStep)"  
						)
						if( checkMsgContent( Term.createTerm("step(TIME)"), Term.createTerm("step(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 robot.forward(payloadArg(0).toInt() )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t015",targetState="handleSonarData",cond=whenEvent("sonardata"),interruptedStateTransitions)
					transition(edgeName="t016",targetState="handleVrinfoMsgReply",cond=whenEvent("vrinfo"))
				}	 
				state("doGetEnvMap") { //this:State
					action { //it:State
						 val Maprep = rpos.getMapRep()  
						answer("getenvmap", "envmap", "envmap($Maprep)"   )  
						updateResourceRep( "map($Maprep)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("domove") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("move(M)"), Term.createTerm("move(M)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Move = payloadArg(0);   
								updateResourceRep( "doing($name,$Move)"  
								)
								if(  Move == "h"  
								 ){ robot.halt()          
								}
								if(  Move == "a" || Move == "l"  
								 ){ robot.turnLeft()    
								 rpos.turnLeft()     
								}
								if(  Move == "d" || Move == "r"  
								 ){ robot.turnRight()    
								 rpos.turnRight()     
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("handleSonarData") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonar(DISTANCE)"), Term.createTerm("sonar(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("$name | handleSonarData ")
								 var D = payloadArg(0)  
								CommUtils.outred("$name |  sonaralarm:distance($D) ----- EMIT ------  ")
								emit("sonaralarm", "distance($D)" ) 
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("tuneAtHome") { //this:State
					action { //it:State
						 val Dir  = rpos.getCurDir()
						    		var res = false
						CommUtils.outmagenta("$name | tuneAtHome Dir=$Dir")
						if(  Dir == "up"  
						 ){  rpos.doMove( "w")   
						CommUtils.outyellow("$name | tuneAtHome upDir ")
						 res = robot.step( 300 )  
						CommUtils.outyellow("$name | tuneAtHome updDir res=$res ")
						 robot.turnLeft()           
						 rpos.doMove( "l" )         
						 res = robot.step( 300 )   
						CommUtils.outyellow("$name | tuneAtHome updDir res=$res ")
						 robot.turnLeft()           
						 rpos.doMove( "l" )         
						CommUtils.outblack("$name |  ${rpos.getCurDir()}")
						}
						else
						 {if(  Dir == "left"  
						  ){  rpos.doMove( "w")   
						  res = robot.step( 300 )   
						 CommUtils.outyellow("$name | tuneAtHome leftDir dostep1 res=$res ")
						  robot.turnRight()        
						  rpos.doMove( "r" )       
						  robot.step( 300 )        
						 CommUtils.outyellow("$name | tuneAtHome leftDir dostep2 res=$res ")
						  robot.turnLeft()   
						  rpos.doMove( "l" )         
						  robot.turnLeft()   
						  rpos.doMove( "l" )         
						 }
						 else
						  {if(  Dir == "down"  
						   ){}
						  }
						 }
						CommUtils.outyellow("$name | tuneAtHome done ")
						answer("tuneAtHome", "tuneDone", "tuneDone(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("handleVrinfoMsgReply") { //this:State
					action { //it:State
						 var NOW = 0L; var TDONE = 0L  
						NOW = getCurrentTime()
						if( checkMsgContent( Term.createTerm("vrinfo(SOURCE,INFO)"), Term.createTerm("vrinfo(S,R)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var S = payloadArg(0)  
								 val R = payloadArg(1)  
								if(  S.contains("ko")  
								 ){ TDONE = NOW - CurTime  
								CommUtils.outmagenta("$name | reply asynchstep failed after $R DT=$TDONE")
								 var DT = TDONE.toInt() / 2  
								 robot.backward( DT)  
								delay(300) 
								 robot.halt()         
								answer("step", "stepfailed", "stepfailed($TDONE,obst)"   )  
								}
								else
								 {answer("step", "stepdone", "stepdone(ok)"   )  
								  rpos.forwardStep()     
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
				state("dosetrobotdirection") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dir(D)"), Term.createTerm("dir(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Dir  = payloadArg(0)  
								 Plan     = rpos.planToSetDirection(Dir)  
								CommUtils.outmagenta("dosetrobotdirection dir=$Dir Plan=$Plan")
								if(  Plan == ""  
								 ){forward("noplan", "noplan(ok)" ,name ) 
								}
								else
								 {forward("changedir", "changedir(ok)" ,name ) 
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="changeDirection",cond=whenDispatch("changedir"))
					transition(edgeName="t018",targetState="setDirReply",cond=whenDispatch("noplan"))
				}	 
				state("changeDirection") { //this:State
					action { //it:State
						
								   if( Plan.length > 0  ){
									   	MoveForDir =  Plan.elementAt(0).toString() 
									   	Plan       =  Plan.removePrefix(MoveForDir)
								   }else{
									   	MoveForDir  = ""
									   	Plan        = ""
								   }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="nextMove", cond=doswitchGuarded({ MoveForDir  != ""  
					}) )
					transition( edgeName="goto",targetState="setDirReply", cond=doswitchGuarded({! ( MoveForDir  != ""  
					) }) )
				}	 
				state("nextMove") { //this:State
					action { //it:State
						if(  MoveForDir == "a" || MoveForDir  == "l"  
						 ){ robot.turnLeft()    
						 rpos.turnLeft()     
						}
						if(  MoveForDir == "d" || MoveForDir  == "r"  
						 ){ robot.turnRight()    
						 rpos.turnRight()     
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="changeDirection", cond=doswitch() )
				}	 
				state("setDirReply") { //this:State
					action { //it:State
						 val PX = rpos.getPosX() 
								   val PY = rpos.getPosY()
						answer("setdirection", "setdirectiondone", "pos($PX,$PY)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitinputmsg", cond=doswitch() )
				}	 
			}
		}
} 
