/* Generated by AN DISI Unibo */ 
package it.unibo.boundaryworker

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Boundaryworker ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var laticompletati = 0
		        val DMIN = 20.0
		        var Intruder = false
		        val StepTime = 350L // Tempo per ogni "passo" elementare
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("boundaryworker | Pronto. In attesa di 'start'.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="doStep",cond=whenDispatch("start"))
					transition(edgeName="t01",targetState="checkRadarHome",cond=whenEvent("radar"))
				}	 
				state("doStep") { //this:State
					action { //it:State
						request("step", "step($StepTime)" ,"robotactor" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t12",targetState="doStep",cond=whenReply("stepdone"))
					transition(edgeName="t13",targetState="handleWallDetected",cond=whenReply("stepfailed"))
					transition(edgeName="t14",targetState="checkRadarWhileMoving",cond=whenEvent("radar"))
				}	 
				state("handleWallDetected") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stepfailed(DURATION,CAUSE)"), Term.createTerm("stepfailed(D,C)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblack("boundaryworker | MURO RILEVATO. Girone a sinistra (l).")
								forward("move", "move(l)" ,"robotactor" ) 
								delay(500) 
								 laticompletati++  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkEnd", cond=doswitch() )
				}	 
				state("checkEnd") { //this:State
					action { //it:State
						CommUtils.outblack("boundaryworker | Lati completati: $laticomplicati")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="home", cond=doswitchGuarded({ laticompletati >= 4  
					}) )
					transition( edgeName="goto",targetState="doStep", cond=doswitchGuarded({! ( laticompletati >= 4  
					) }) )
				}	 
				state("checkRadarWhileMoving") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Dist = payloadArg(0).toDouble()  
								if(  Dist < DMIN  
								 ){CommUtils.outblack("boundaryworker | INTRUSO! Stop (h).")
								 Intruder = true  
								forward("move", "move(h)" ,"robotactor" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="stoppedByRadar", cond=doswitchGuarded({ Intruder  
					}) )
					transition( edgeName="goto",targetState="doStep", cond=doswitchGuarded({! ( Intruder  
					) }) )
				}	 
				state("stoppedByRadar") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t25",targetState="checkClearWhileStopped",cond=whenEvent("radar"))
				}	 
				state("checkClearWhileStopped") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Dist = payloadArg(0).toDouble()  
								if(  Dist >= DMIN  
								 ){CommUtils.outblack("boundaryworker | Libero. Riprendo.")
								 Intruder = false  
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="doStep", cond=doswitchGuarded({ !Intruder  
					}) )
					transition( edgeName="goto",targetState="stoppedByRadar", cond=doswitchGuarded({! ( !Intruder  
					) }) )
				}	 
				state("home") { //this:State
					action { //it:State
						CommUtils.outblack("boundaryworker | In HOME. Ciclo terminato.")
						forward("move", "move(h)" ,"robotactor" ) 
						 laticompletati = 0  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t36",targetState="doStep",cond=whenDispatch("start"))
					transition(edgeName="t37",targetState="checkRadarHome",cond=whenEvent("radar"))
				}	 
				state("checkRadarHome") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Dist = payloadArg(0).toDouble()  
								if(  Dist < DMIN  
								 ){CommUtils.outblack("boundaryworker | INTRUSO IN HOME! Rotazione (l).")
								 Intruder = true  
								forward("move", "move(l)" ,"robotactor" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="rotatingAtHome", cond=doswitchGuarded({ Intruder  
					}) )
					transition( edgeName="goto",targetState="home", cond=doswitchGuarded({! ( Intruder  
					) }) )
				}	 
				state("rotatingAtHome") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t48",targetState="checkClearInHome",cond=whenEvent("radar"))
				}	 
				state("checkClearInHome") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Dist = payloadArg(0).toDouble()  
								if(  Dist >= DMIN  
								 ){CommUtils.outblack("boundaryworker | Libero. Stop rotazione.")
								 Intruder = false  
								forward("move", "move(h)" ,"robotactor" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="home", cond=doswitchGuarded({ !Intruder  
					}) )
					transition( edgeName="goto",targetState="rotatingAtHome", cond=doswitchGuarded({! ( !Intruder  
					) }) )
				}	 
			}
		}
} 
